### ISSUE TITLE
First feedback - issue #1 !!

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/Compact-Power-Card#1]
Do I get a prize for being the first to raise an issue and give feedback?

First of all, great to see the development, be interesting to see how it evolves.

I'll start off by saying (and setting the bar for 'what good looks like' to me), I use the PowerFlow+ card,  I like the iconography and simple uncluttered look, but its not without its limitations, principally that it can only display a single solar/battery setup so I have to duplicate everything for my two inverters.  So being able to display both inverters, batteries and ideally all 3 solar arrays on a single card is where I'd like to get to.

PF+ looks like this:
<img width="905" height="381" alt="Image" src="https://github.com/user-attachments/assets/f4f4dc74-3bf8-4947-af27-b85dcdc4fc87" />

I have an 'almost working' combined PF+ with both inverters, using individual devices as additional solar arrays and batteries, so this is ideally where I want to get to:
<img width="919" height="396" alt="Image" src="https://github.com/user-attachments/assets/e8eaa254-c85c-4569-a4b1-f176499e5952" />

Feedback on setting up the compact power flow card.  First thing I notice is it is compact, too compact!  I don't seem to be able to increase the size of it on a sections dashboard despite setting it to 4 columns with.  Some form of override of row and column size as is done for Apex charts would be useful.
<img width="304" height="139" alt="Image" src="https://github.com/user-attachments/assets/1cf352cb-91fc-4fa7-9172-860fdc8dfdd0" />

Second, several entities are greyed out, I don't understand why.  Thought it might be due to the additional dummy house devices so I deleted them, but still greyed out.

Config:
```
type: custom:compact-power-card
threshold_mode: calculations
entities:
  pv:
    entity: sensor.total_solar_power
    color: var(--energy-solar-color)
    threshold: 50
    decimal_places: 1
    labels:
      - entity: sensor.solar_energy_today
        unit: kWh
        color: "#ffb300"
  grid:
    entity: sensor.g_sd2237g182_grid_power
    invert_state_values: false
    threshold: 25
    labels:
      - entity: sensor.g_sd2237g182_grid_voltage
        icon: mdi:lightning-bolt
        unit: V
  battery:
    entity: sensor.g_sd2237g182_battery_power
    invert_state_values: false
    threshold: 25
    labels:
      - entity: sensor.g_sd2237g182_soc
        unit: "%"
```

I tried adding multiply batteries but it wasn't having it!

In your readme can you add an example of how the labels work?

"Aux sources".  Personally I think the terminology is wrong, these should be "individual devices", they are not really power sources, more power consumers or consumption devices.  Sources to me speaks of generators, etc.

Edit: I worked out that the reason things were greyed out was the thresholds. The logic and units doesn't seem right.
House is greyed out if battery is below threshold, shouldn't house always be visible?

Changing the config:
```
type: custom:compact-power-card
threshold_mode: calculations
entities:
  pv:
    entity: sensor.total_solar_power
    color: var(--energy-solar-color)
    threshold: 50
    decimal_places: 1
    labels:
      - entity: sensor.solar_energy_today
        unit: kWh
        color: "#ffb300"
  grid:
    entity: sensor.g_sd2237g182_grid_power
    invert_state_values: false
    threshold: 0
    labels:
      - entity: sensor.g_sd2237g182_grid_voltage
        icon: mdi:lightning-bolt
        unit: V
  battery:
    entity: sensor.g_sd2237g182_battery_power
    invert_state_values: false
    threshold: 0.6
    labels:
      - entity: sensor.g_sd2237g182_soc
        unit: "%"
```

House now appears but load is calculated as 0.2W not 0.2kW

<img width="420" height="189" alt="Image" src="https://github.com/user-attachments/assets/69654208-9c25-4a31-bac1-07a9d5a32eea" />

I use kW as the UOM for all of my entities as its easier to read quickly than reading super-precise watt values but the template thresholds were all in watts, so hence why everything was greyed out. 
Ideally I'd like the ability for the card to be able to show watts or kW depending on the size of the power flow.  Maybe there needs to be rules as to what units the thresholds are configured in, e.g. always have to be configured in watts rather than UOM of the entity?  At the moment they need to match the entity UOM, but at least values like 0.6 did work OK

Not something I need, but you may need to support separate grid import/export and battery charge/discharge power sensors as some inverters work like that.

Like the ability to decide whether aux sources are included or excluded from the home, that could be useful.

I don't personally like the icons in use, and yes I know I can change them.  Maybe its because there is so much crowded next to the icons whereas the PF+ has similar icons but with more white space?

Anyway, first set of comments, thanks

**Comment by F17HEH** [comment]
I really like the look of this but the power lines are not working for me, Not sure what im missing?

<img width="451" height="182" alt="Image" src="https://github.com/user-attachments/assets/352ba34c-ac32-4248-ba78-ad900efecbad" />

**Comment by F17HEH** [comment]
well ive set the thresholds to 0.1 and the icons work, the power flow lines are not.  Looking at the documentation they should use the same thresholds.  Really do like the look of this tho

**Comment by pacemaker82** [comment]
Significant update to usability here: https://github.com/pacemaker82/Compact-Power-Card/releases/tag/v1.1.3

Important: Please adjust your thresholds to be set in watts. The card will convert the source entities to watts even if set to kW. The display logic should be consistent.

@gcoan threshold behaviour should be aligned with power flow card. 

## Added

- Regardless of power source config (watts, kW, mW), the card will convert to watts and display appropriately.

## Fixed

- Glow effect removed when card is in light mode
- Icons no longer fade when power value is 0, only the power label.
- Adjusted opacity when power elements are disabled via thresholds. Icon is always illuminated, power label disappears.
- Decimal place config is now ignored when label is showing watts.

**Comment by gcoan** [comment]
thanks, these all sound excellent improvements.  I have to go out now so it'll be later on that I install and test, but thank you.  Early morning coding ?

**Comment by pacemaker82** [comment]
>Early morning coding ? 

Before my wife makes me do jobs, yes 😄 

I've bumped the default font size for the next release which is a big improvement, I will continue to tweak (before and after):

<img width="287" height="212" alt="Image" src="https://github.com/user-attachments/assets/e398ed48-a4f6-40de-a1c5-a9c3bf3adbbb" /><img width="286" height="211" alt="Image" src="https://github.com/user-attachments/assets/ee5fd9bc-1fa7-4c69-a405-b02706740d3c" />

**Comment by gcoan** [comment]
Installed 1.1.4

First feedback, looks much better, more readable.

The card seems to be narrower as well, not changed anything and it's now not taking up the same width as the PF+ above.

Text size better, icons still look a bit tiny, but its personal I guess

Not had a chance to look at the thresholds yet, and also how to configure the card to show kW UoM rather than Watts
![image](https://github.com/user-attachments/assets/dd2ad9cc-aaca-4568-958f-19b44a907b6c)

One additional observation it appears to have a transparent background rather than white which all other cards (not just PF+, the predbat plan card, entities card, etc are all white background) have

**Comment by pacemaker82** [comment]
I've bumped the icon size and fixed the background in the next release. 

In terms of the width of the card, I didnt mess with that - something odd there. Would you mind sharing the entire YAML of that page so I can see whats going on? Or share how you have it configured in the sections UI

**Comment by pacemaker82** [comment]
Thanks. I think I have implemented support for rows/columns in the sections UI! Check out new version https://github.com/pacemaker82/Compact-Power-Card/releases/tag/v1.1.5 

<img width="1056" height="554" alt="Image" src="https://github.com/user-attachments/assets/e825112a-21b9-4143-aba0-68eb340d4ae8" />

**Comment by gcoan** [comment]
> Important: Please adjust your thresholds to be set in watts. The card will convert the source entities to watts even if set to kW. The display logic should be consistent.

this bit of the readme is I think now wrong:

"threshold should be set based on the source unit of measurement. So "0.1" if kW versus "100" if watts."

**Comment by gcoan** [comment]
I've changed all the thresholds to now be in watts, the thresholds are working fine for PV and grid, correctly suppressing tiny in/out values.

But for individual devices and multi-batteries, they don't appear to be working, see indicated entries which are greyed but still showing a value when mode is set to calculation 
![image](https://github.com/user-attachments/assets/566af3af-708a-4a20-8175-5efb64515916)

**Comment by pacemaker82** [comment]
Thanks will take a look at both the section issue and the thresholds. I’m not sure the section issue is me. All the card does is stretch to whatever HA is set to show, but will take a look

**Comment by pacemaker82** [comment]
@gcoan not a big fan of copying the hiding of the labels for the other power sources when threshold not met, makes it feel a bit broken.

<img width="801" height="232" alt="Image" src="https://github.com/user-attachments/assets/d3fd9ca9-ec61-41fd-a7f1-55b34eb29387" />

**Comment by F17HEH** [comment]
OK that is working, had to remove the unit per sensor but looking good.

**Comment by gcoan** [comment]
Probably need to update the About on Github as this is misleading

![image](https://github.com/user-attachments/assets/37865487-c7ff-4cfe-9d0b-2d9182d485e4)
